# Generated by Django 4.1 on 2022-10-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0003_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycartitem',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
