# Generated by Django 4.1 on 2022-10-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0004_mycartitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycartitem',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mycartitem',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
