# Generated by Django 4.1 on 2022-10-29 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productcolor_productsize_product_color_product_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycart', '0005_mycartitem_color_mycartitem_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
